name: Latest Blogs
on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:
  
jobs:
  update-readme-with-devto-blogs  :
    name: Update this repo's README with latest activity from Dev.to
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "Dev.to"
          commit_message: "Updated README with the latest Dev.to Post"
          feed_list: "https://dev.to/feed/j471n"
